name: testtest
        
on:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'


# 定时触发编译(每天早5点)
#  schedule:
#    - cron: 0 21 * * *

# 点赞☆Star触发编译
#  watch:
#    types: [started]

jobs:
  deploy:
    runs-on: ubuntu-latest # 使用ubuntu系统镜像运行自动化脚
    name: 编译 ${{matrix.target}}
    strategy:
      fail-fast: false
      matrix:
        target: [All_RM2100]  #[Lean_x86_64,All_RM2100,Sim_RM2100,Ap_RM2100,Lienol_x86_64,]

    steps: # 自动化步骤
      - uses: actions/checkout@v2 # 第一步，下载代码仓库
    
      - name: 上传到固件到网盘
        uses: AEnterprise/rsync-deploy@v1.0  
        env:
           DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }} 
           ARGS: -avz --delete --exclude='*.pyc'
           SERVER_PORT: ${{ secrets.SERVER_PORT }}
           FOLDER: ./
           SERVER_IP: ${{ secrets.SSH_HOST }} 
           USERNAME: ${{ secrets.SSH_USERNAME }} 
           SERVER_DESTINATION: /mnt/disk2/appdata/Test/
           
      - name: 进入目录删除
        run: |
         cd /home/runner/work/_temp/_github_home/
         sudo rm -rf .ssh

      - name: 上传到固件到网盘
        uses: AEnterprise/rsync-deploy@v1.0  
        env:
           DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }} 
           ARGS: -avz --delete --exclude='*.pyc'
           SERVER_PORT: ${{ secrets.SERVER_PORT }}
           FOLDER: ./
           SERVER_IP: ${{ secrets.SSH_HOST }} 
           USERNAME: ${{ secrets.SSH_USERNAME }} 
           SERVER_DESTINATION: /mnt/disk2/appdata/Test/
           
   #-avz --delete --exclude='*.pyc'
