name: Deploy site files

on:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'


# 定时触发编译(每天早5点)
#  schedule:
#    - cron: 0 21 * * *

# 点赞☆Star触发编译
#  watch:
#    types: [started]

jobs:
  deploy:
    runs-on: ubuntu-latest # 使用ubuntu系统镜像运行自动化脚本

    steps: # 自动化步骤
      - uses: actions/checkout@v2 # 第一步，下载代码仓库

      - name: 上传到固件到网盘
        uses: AEnterprise/rsync-deploy@v1.0  
        env:
           DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }} 
           ARGS: -avz --delete --exclude='.pry'
           SERVER_PORT: ${{ secrets.SERVER_PORT }}
           FOLDER: ./
           SERVER_IP: ${{ secrets.SSH_HOST }} 
           USERNAME: ${{ secrets.SSH_USERNAME }} 
           SERVER_DESTINATION: ${{ secrets.SERVER_DESTINATION }}
